apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    component: webapp
  name: {{ .Release.Name }}-webapp-lb
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}
    component: webapp
  loadBalancerSourceRanges:
    - 35.208.227.25/32
    - 35.184.28.238/32
  type: LoadBalancer
